# cloudbuild.yaml

# Define sustituciones que se usarán en los pasos.
substitutions:
  _MY_PROJECT_ID: golden-tempest-469108-r4
  _MY_REGION: us-central1
  _MY_AR_REPO: control-pallets-repo
  _MY_IMAGE_NAME: control-pallets
  _MY_SERVICE_NAME: control-pallets-app
  # Asegúrate de que esta instancia de Cloud SQL sea correcta para tu proyecto.
  _SQL_INSTANCE: golden-tempest-469108-r4:us-central1:recepcion-sql-db

# Define los pasos que se ejecutarán en Cloud Build.
steps:
  # Paso 1: Construir la imagen de Docker.
  # Usa la imagen de Cloud Builders para Docker.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    # --- MODIFICACIÓN CLAVE AQUÍ ---
    # Aseguramos que cada argumento se trate como una cadena separada.
    # Usamos '--tag' explícitamente y envolvemos los argumentos entre comillas.
    args:
      - 'build'
      - '--tag=${_MY_REGION}-docker.pkg.dev/${_MY_PROJECT_ID}/${_MY_AR_REPO}/${_MY_IMAGE_NAME}:${COMMIT_SHA}'
      - '.' # El '.' indica que el contexto de construcción es el directorio actual.
    # --- FIN DE LA MODIFICACIÓN ---

  # Paso 2: Subir la imagen de Docker construida a Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args:
      - 'push'
      - '${_MY_REGION}-docker.pkg.dev/${_MY_PROJECT_ID}/${_MY_AR_REPO}/${_MY_IMAGE_NAME}:${COMMIT_SHA}'

  # Paso 3: Desplegar la imagen en Cloud Run.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_MY_SERVICE_NAME}'
      - '--image=${_MY_REGION}-docker.pkg.dev/${_MY_PROJECT_ID}/${_MY_AR_REPO}/${_MY_IMAGE_NAME}:${COMMIT_SHA}'
      - '--region=${_MY_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=${_SQL_INSTANCE}'
      - '--set-env-vars=DB_SERVER=34.171.224.221,DB_USER=sqlserver,DB_PASSWORD=Aventura54,DB_DATABASE=Recepcion'
      - '--port=8080'

# Lista de imágenes que se guardarán en Artifact Registry (opcional, pero buena práctica).
images:
  - '${_MY_REGION}-docker.pkg.dev/${_MY_PROJECT_ID}/${_MY_AR_REPO}/${_MY_IMAGE_NAME}:${COMMIT_SHA}'

# Opciones de construcción.
options:
  # Configura el logging para enviar solo a Cloud Logging.
  logging: CLOUD_LOGGING_ONLY